# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
 
target 'FIRDBExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 
  # Pods for FIRDBExample
  pod 'Firebase/Database'
 
  target 'FIRDBExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end
 
  target 'FIRDBExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end
 
end